"""
URAR Form Field Definitions and Confidence Thresholds

Defines the structure of URAR (Uniform Residential Appraisal Report) forms
and critical field requirements for cost segregation analysis.
"""

from typing import Dict, List

# Critical fields that require high confidence (>= 0.90)
# These are essential for cost segregation calculations
CRITICAL_FIELDS: List[str] = [
    "property_address",
    "year_built",
    "gross_living_area",
    "appraised_value",
    "contract_price",
    "effective_date",
]

# Confidence thresholds by field importance
CONFIDENCE_THRESHOLDS: Dict[str, float] = {
    "critical": 0.90,   # Must meet this for critical fields
    "standard": 0.85,   # Standard threshold for other fields
    "minimum": 0.50,    # Below this, mark as needs_review
}

# Source confidence baselines
SOURCE_CONFIDENCE: Dict[str, tuple] = {
    "mismo_xml": (1.0, 1.0),           # Always authoritative
    "azure_di": (0.70, 0.95),          # Range based on clarity
    "gpt4o_vision": (0.60, 0.90),      # Range based on complexity
    "regex": (0.50, 0.80),             # Range based on match quality
}

# URAR Section definitions with their fields
# Maps to the frontend AppraisalResources interface
URAR_SECTIONS: Dict[str, List[str]] = {
    "subject": [
        "property_address",
        "city",
        "state",
        "zip",
        "borrower",
        "owner_of_public_record",
        "county",
        "legal_description",
        "assessors_parcel",
        "tax_year",
        "real_estate_taxes",
        "neighborhood_name",
        "map_reference",
        "census_tract",
        "occupant",
        "special_assessments",
        "pud",
        "hoa_dues",
        "property_rights_appraised",
    ],
    "listing_and_contract": [
        "data_sources_for_listing_history",
        "offering_price",
        "listing_date",
        "days_on_market",
        "data_sources_for_sales_history",
        "prior_sale_date",
        "prior_sale_price",
        "sale_type",
        "contract_price",
        "contract_date",
        "seller_concessions",
        "financing_type",
        "lender_client",
    ],
    "neighborhood": [
        "location",
        "built_up",
        "growth",
        "property_values",
        "demand_supply",
        "marketing_time",
        "present_land_use_one_unit",
        "present_land_use_two_to_four",
        "present_land_use_multi_family",
        "present_land_use_commercial",
        "present_land_use_other",
        "neighborhood_boundaries",
        "neighborhood_description",
        "market_notes",
    ],
    "site": [
        "dimensions",
        "area_acres",
        "area_sqft",
        "shape",
        "view",
        "zoning_classification",
        "zoning_description",
        "zoning_compliance",
        "highest_and_best_use",
        "utilities_electric",
        "utilities_gas",
        "utilities_water",
        "utilities_sewer",
        "off_site_improvements_street",
        "off_site_improvements_alley",
        "fema_flood_zone",
        "fema_map_number",
        "fema_map_date",
        "flood_insurance_required",
        "topography",
        "drainage",
        "easements",
        "encroachments",
        "special_flood_hazard",
    ],
    "improvements": [
        "general_description_units",
        "general_description_stories",
        "general_description_type",
        "general_description_design_style",
        "year_built",
        "effective_age",
        "foundation_type",
        "foundation_slab",
        "foundation_crawl",
        "foundation_basement",
        "foundation_sump_pump",
        "foundation_dampness",
        "foundation_settlement",
        "foundation_infestation",
        "exterior_walls",
        "roof_surface",
        "gutters_downspouts",
        "window_type",
        "storm_sash_insulated",
        "screens",
        "manufactured_housing",
        "basement_area_sqft",
        "basement_finished_sqft",
        "basement_ceiling",
        "basement_walls",
        "basement_floor",
        "basement_outside_entry",
        "insulation_roof",
        "insulation_ceiling",
        "insulation_walls",
        "insulation_floor",
        "insulation_unknown",
        "heating_type",
        "heating_fuel",
        "heating_condition",
        "cooling_central",
        "cooling_other",
        "cooling_condition",
        "amenities_fireplace",
        "amenities_patio_deck",
        "amenities_pool",
        "amenities_fence",
        "amenities_porch",
        "amenities_other",
        "appliances_included",
        "car_storage_none",
        "car_storage_garage_spaces",
        "car_storage_carport_spaces",
        "car_storage_driveway_spaces",
        "car_storage_attached",
        "car_storage_detached",
        "car_storage_built_in",
        "finished_area_above_grade",
        "rooms_above_grade",
        "bedrooms_above_grade",
        "bathrooms_above_grade",
        "gross_living_area",
        "square_feet_gla",
        "additional_features",
        "interior_condition",
        "physical_deficiencies",
        "adverse_conditions",
    ],
    "interior_mechanical": [
        "interior_floors",
        "interior_walls",
        "interior_trim_finish",
        "interior_bath_floor",
        "interior_bath_wainscot",
        "interior_doors",
        "interior_condition",
        "attic_none",
        "attic_stairs",
        "attic_drop_stair",
        "attic_scuttle",
        "attic_floor",
        "attic_heated",
        "attic_finished",
        "mechanical_adequacy",
        "mechanical_condition",
        "gross_living_area",
        "rooms_above_grade",
    ],
    "sales_comparison": [
        "subject_price_per_gla",
        "subject_total_rooms",
        "comparable_1",
        "comparable_2",
        "comparable_3",
        "summary_of_sales_comparison",
        "indicated_value_by_sales_comparison",
    ],
    "cost_approach": [
        "support_for_cost_approach",
        "estimated_site_value",
        "dwelling_size_sqft",
        "dwelling_cost_per_sqft",
        "dwelling_total_cost",
        "extras_description",
        "extras_cost",
        "garage_carport_size",
        "garage_carport_cost",
        "total_cost_new",
        "depreciation_physical",
        "depreciation_functional",
        "depreciation_external",
        "depreciation_total",
        "depreciated_cost_improvements",
        "as_is_value_site_improvements",
        "indicated_value_by_cost_approach",
        "site_value",
    ],
    "reconciliation": [
        "indicated_value_sales_comparison",
        "indicated_value_cost_approach",
        "indicated_value_income_approach",
        "reconciliation_summary",
        "final_opinion_of_market_value",
        "effective_date",
        "appraiser_name",
        "appraiser_signature_date",
        "supervisory_appraiser_name",
    ],
}

# MISMO XML path mappings for Tier 1 extraction
# Maps MISMO XML XPath expressions to our field structure
MISMO_FIELD_MAPPINGS: Dict[str, str] = {
    # Subject section
    "//PROPERTY/ADDRESS/StreetAddress": "subject.property_address",
    "//PROPERTY/ADDRESS/City": "subject.city",
    "//PROPERTY/ADDRESS/State": "subject.state",
    "//PROPERTY/ADDRESS/PostalCode": "subject.zip",
    "//PROPERTY/ADDRESS/County": "subject.county",
    "//PROPERTY/LegalDescription": "subject.legal_description",
    "//PROPERTY/ParcelIdentificationNumber": "subject.assessors_parcel",

    # Contract/Listing section
    "//CONTRACT/ContractPrice": "listing_and_contract.contract_price",
    "//CONTRACT/ContractDate": "listing_and_contract.contract_date",
    "//CONTRACT/SellerConcessions": "listing_and_contract.seller_concessions",

    # Improvements section
    "//IMPROVEMENTS/YearBuilt": "improvements.year_built",
    "//IMPROVEMENTS/GrossLivingArea": "improvements.gross_living_area",
    "//IMPROVEMENTS/BasementArea": "improvements.basement_area_sqft",
    "//IMPROVEMENTS/Stories": "improvements.general_description_stories",
    "//IMPROVEMENTS/Bedrooms": "improvements.bedrooms_above_grade",
    "//IMPROVEMENTS/Bathrooms": "improvements.bathrooms_above_grade",

    # Site section
    "//SITE/SiteArea": "site.area_sqft",
    "//SITE/ZoningClassification": "site.zoning_classification",
    "//SITE/FloodZone": "site.fema_flood_zone",

    # Reconciliation section
    "//APPRAISAL/AppraisedValue": "reconciliation.final_opinion_of_market_value",
    "//APPRAISAL/EffectiveDate": "reconciliation.effective_date",
    "//APPRAISAL/AppraiserName": "reconciliation.appraiser_name",

    # Cost Approach section
    "//COST_APPROACH/SiteValue": "cost_approach.site_value",
    "//COST_APPROACH/TotalCostNew": "cost_approach.total_cost_new",
    "//COST_APPROACH/Depreciation": "cost_approach.depreciation_total",
}

# Azure Document Intelligence field mappings
# Maps Azure DI key-value pairs to our field structure
AZURE_DI_KEY_MAPPINGS: Dict[str, str] = {
    "Property Address": "subject.property_address",
    "City": "subject.city",
    "State": "subject.state",
    "Zip Code": "subject.zip",
    "Borrower": "subject.borrower",
    "Owner of Public Record": "subject.owner_of_public_record",
    "County": "subject.county",
    "Legal Description": "subject.legal_description",
    "Assessor's Parcel #": "subject.assessors_parcel",
    "Tax Year": "subject.tax_year",
    "R.E. Taxes": "subject.real_estate_taxes",
    "Contract Price": "listing_and_contract.contract_price",
    "Date of Contract": "listing_and_contract.contract_date",
    "DOM": "listing_and_contract.days_on_market",
    "Lender/Client": "listing_and_contract.lender_client",
    "Year Built": "improvements.year_built",
    "Effective Age": "improvements.effective_age",
    "Gross Living Area": "improvements.gross_living_area",
    "Stories": "improvements.general_description_stories",
    "Design (Style)": "improvements.general_description_design_style",
    "Basement Area": "improvements.basement_area_sqft",
    "Rooms": "improvements.rooms_above_grade",
    "Bedrooms": "improvements.bedrooms_above_grade",
    "Bath(s)": "improvements.bathrooms_above_grade",
    "Location": "neighborhood.location",
    "Built-Up": "neighborhood.built_up",
    "Growth": "neighborhood.growth",
    "Dimensions": "site.dimensions",
    "Site Area": "site.area_sqft",
    "Zoning Classification": "site.zoning_classification",
    "FEMA Flood Zone": "site.fema_flood_zone",
    "Site Value": "cost_approach.site_value",
    "Total Cost New": "cost_approach.total_cost_new",
    "Indicated Value by Sales Comparison": "reconciliation.indicated_value_sales_comparison",
    "Indicated Value by Cost Approach": "reconciliation.indicated_value_cost_approach",
    "Final Opinion of Market Value": "reconciliation.final_opinion_of_market_value",
    "Effective Date": "reconciliation.effective_date",
    "Appraiser": "reconciliation.appraiser_name",
}
